//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class catagory
    {
        public catagory()
        {
            this.ads = new HashSet<ad>();
        }

     //   [Required(ErrorMessage = "Please select at least one option")]
        public int Id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<ad> ads { get; set; }
    }
}
