//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Country
    {
        public Country()
        {
            this.addres = new HashSet<addre>();
            this.states = new HashSet<state>();
        }

      //  [Required(ErrorMessage = "Please select at least one option")]
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<addre> addres { get; set; }
        public virtual ICollection<state> states { get; set; }
    }
}
