//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class state
    {
        public state()
        {
            this.addres = new HashSet<addre>();
            this.cities = new HashSet<city>();
        }

   //     [Required(ErrorMessage = "Please select at least one option")]
        public int Id { get; set; }
        public string name { get; set; }
        public int country { get; set; }
    
        public virtual ICollection<addre> addres { get; set; }
        public virtual ICollection<city> cities { get; set; }
        public virtual Country Country1 { get; set; }
    }
}
